require("core.plugin_config.go")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gruvbox")
require("core.plugin_config.treesitter")
require("core.plugin_config.cmp")
require("core.plugin_config.copilot")
